# version: '3.1'

# services:
#   postgres:
#     image: postgres
#     network_mode: host
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_PASSWORD: 'postgres'
#       POSTGRES_USER: 'postgres'

#   # adminer:
#   #   image: adminer
#   #   restart: always
#   #   ports:
#   #     - 8080:8080